/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppExploreIndexRouteImport } from './routes/_app/explore/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExploreIndexRoute = AppExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/$': typeof AppSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/explore/': typeof AppExploreIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof AppSplatRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/explore': typeof AppExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/explore/': typeof AppExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/api/auth/$' | '/explore/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/' | '/api/auth/$' | '/explore'
  id:
    | '__root__'
    | '/_app'
    | '/_app/$'
    | '/_app/'
    | '/api/auth/$'
    | '/_app/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/explore/': {
      id: '/_app/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof AppExploreIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExploreIndexRoute: typeof AppExploreIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppIndexRoute: AppIndexRoute,
  AppExploreIndexRoute: AppExploreIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
